#!/usr/bin/env perl

use strict;
use warnings;

use Encode::Base32::Crockford qw/:all/;

srand time;

for ( 0 .. 7 ) {
    my $number = int rand time;
    my $string = lc base32_encode $number;
    print "$number $string\n";
}

for ( 0 .. 7 ) {
    my $number = int rand time;
    my $string = lc sprintf '%x', $number;
    print "$number $string\n";
}
